/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ekpyeqhwktjsxdnnqhvp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrcHllcWh3a3Rqc3hkbm5xaHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5NDA0NzYsImV4cCI6MjA4NTUxNjQ3Nn0.zKCCa-gZQWMff6XTAk3YrWiJaG2A4-QuNKa7u0SlnhY"